### PR TITLE
Always add MediaLines to track source

### LINKED ISSUE #426: MediaLines on track source are not always initialized
They are only set when setting `Source` on a MediaLine at runtime. 

This causes an exception if there is a call active and the shutdown order is such that the source is destroyed before the PC. This in turn seems to cause dangling resources with consequent freezing Unity editor on close/play again.

### PR DESCRIPTION
**Pull request by fibann**
The fix is in MediaLine.OnAfterDeserialize. The rest is small refactorings/simplifications.

This fixes #426. The behavior is still a bit weird - we are removing the source from the MediaLine when it is disabled, but have no way to re-add it when it is re-enabled.

### CODE REVIEW

File: libs/unity/library/Runtime/Scripts/Media/MediaLine.cs [hunk 1]
```diff
@@ -552,18 +515,22 @@ internal void UpdateOnReceiveAnswer()
...
+
+        public void OnBeforeSerialize() {}
+
+        public void OnAfterDeserialize()
+        {
+            if (_source)
             {
-                videoTrack.Dispose();
+                // Fill the list of media lines for the source.
+                ((IMediaTrackSourceInternal)_source).OnAddedToMediaLine(this);
```
Comment (djee-ms) [inline libs/unity/library/Runtime/Scripts/Media/MediaLine.cs:532]: `OnAddedToMediaLine()` asserts that the media line list doesn't contain this source already, but `OnAfterDeserialize()` is called in many places, including apparently when cloning an object, and not necessarily only when the current object is created/loaded the first time (see [docs](https://docs.unity3d.com/ScriptReference/ISerializationCallbackReceiver.html)). So `OnAddedToMediaLine()` should probably be updated to avoid asserting.

Comment (fibann) [reply libs/unity/library/Runtime/Scripts/Media/MediaLine.cs:532]: It shouldn't be called twice on the same object though, right?

Comment (djee-ms) [reply libs/unity/library/Runtime/Scripts/Media/MediaLine.cs:532]: No idea, the docs seem to say it is...

Comment (fibann) [reply libs/unity/library/Runtime/Scripts/Media/MediaLine.cs:532]: The docs say
> Serialization can occur during all kinds of operations. For example, when using Instantiate() to clone an object, Unity serializes and deserializes the original object

IMHO they seem to suggest to be aware that those callbacks might be called at runtime, in addition to when files are loaded from disk. They don't seem to imply that callbacks might be called arbitrarily on an object that has already been deserialized. So I see no problem here.

Comment (djee-ms) [reply libs/unity/library/Runtime/Scripts/Media/MediaLine.cs:532]: Fine. "Unity serializes and deserializes the original object" tells me they do are calling it, but on the other hand that makes no sense to deserialize the source object of a clone, so let's assume it's poor wording.

Comment (fibann) [reply libs/unity/library/Runtime/Scripts/Media/MediaLine.cs:532]: I agree it sounds weird but it's reasonable to assume that they mean "serializes the original object and deserializes the serialized original object" 😄
